name: publish
on:
  push:
    branches: [ "feature/hostname-publish" ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
              docker build . --pull -t ghcr.io/falahati/sslh/sslh:hostname
              docker push ghcr.io/falahati/sslh/sslh:hostname
